# Generated by Django 2.2.1 on 2019-06-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='quarterback_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
