# Generated by Django 2.2.2 on 2019-06-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_quarterback_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='receiver_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='running_back_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
