# Generated by Django 2.2.2 on 2019-06-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_last_year_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='quarterbacks_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='receivers_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='running_backs_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
