# Generated by Django 2.2.2 on 2019-06-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190613_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='all_eyes_on_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
