# Generated by Django 3.1 on 2021-08-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200828_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('points', models.FloatField()),
                ('games_played', models.IntegerField()),
                ('rushing_yards', models.IntegerField()),
                ('rushing_tds', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('receiving_tds', models.IntegerField()),
                ('passing_yards', models.IntegerField()),
                ('passing_tds', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.player')),
            ],
        ),
    ]
