# Generated by Django 3.1 on 2021-08-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_playerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='receptions',
            field=models.IntegerField(default=0),
        ),
    ]
